# Generated by Django 6.0.5 on 2026-05-10 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keycloak_sub', models.UUIDField(db_index=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('language', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('fr', 'French')], default='en', max_length=5)),
                ('timezone', models.CharField(default='America/Toronto', max_length=50)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('creator', 'Content Creator'), ('admin', 'Administrator')], default='student', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='accounts.userprofile')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_set', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'User Follow',
                'verbose_name_plural': 'User Follows',
                'db_table': 'user_follows',
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
