# Generated by Django 6.0.5 on 2026-05-12 00:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('user_input', models.TextField(help_text='Original natural-language request for the animation')),
                ('concept_analysis', models.JSONField(blank=True, default=dict)),
                ('scene_design', models.JSONField(blank=True, default=dict)),
                ('generated_code', models.TextField(blank=True)),
                ('rendered_output_url', models.URLField(blank=True, max_length=500)),
                ('output_mode', models.CharField(choices=[('video', 'Video (MP4)'), ('image', 'Image (PNG)')], default='video', max_length=10)),
                ('quality', models.CharField(choices=[('low', 'Low (fast)'), ('medium', 'Medium'), ('high', 'High (slow)')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analysis', 'Concept Analysis'), ('design', 'Scene Design'), ('coding', 'Code Generation'), ('rendering', 'Rendering'), ('done', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animation_projects', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Animation Project',
                'verbose_name_plural': 'Animation Projects',
                'db_table': 'animation_projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GeoGebraSketch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('source', models.CharField(choices=[('expression', 'Math Expression'), ('image', 'Image Analysis'), ('manual', 'Manual Editing')], default='manual', max_length=20)),
                ('expression', models.TextField(blank=True)),
                ('ggb_commands', models.TextField(blank=True, help_text='GeoGebra Classic scripting commands, one per line')),
                ('image_data', models.TextField(blank=True, help_text='Base64-encoded source image (for image-based sketches)')),
                ('bbox_elements', models.JSONField(blank=True, default=list)),
                ('constraints', models.JSONField(blank=True, default=list)),
                ('geometric_relations', models.JSONField(blank=True, default=list)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geogebra_sketches', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'GeoGebra Sketch',
                'verbose_name_plural': 'GeoGebra Sketches',
                'db_table': 'geogebra_sketches',
                'ordering': ['-updated_at'],
            },
        ),
    ]
