# Generated by Django 6.0.5 on 2026-05-10 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('manual', 'Manual Creation'), ('crawler', 'Web Crawler'), ('import', 'File Import'), ('ai_generated', 'AI Generated')], default='manual', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('metadata', models.JSONField(default=dict, help_text='Source-specific metadata (e.g., crawl date, import file)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzle_sources', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'puzzle_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('short_answer', 'Short Answer'), ('long_answer', 'Long Answer'), ('problem_solving', 'Problem Solving'), ('proof', 'Proof'), ('coding', 'Coding Challenge'), ('puzzle', 'Logic Puzzle')], max_length=20)),
                ('subject', models.CharField(choices=[('math', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('literacy', 'Literacy'), ('arts', 'Arts'), ('logic', 'Logic'), ('general', 'General')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('content', models.JSONField(default=dict, help_text='Block-based puzzle content')),
                ('solution', models.JSONField(default=dict, help_text='Solution with steps')),
                ('hints', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('curriculum_references', models.JSONField(default=list, help_text="[{'region': 'Canada-ON', 'grade': '10', 'strand': 'Algebra'}]")),
                ('times_used', models.IntegerField(default=0)),
                ('times_solved', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles_created', to='accounts.userprofile')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puzzles', to='puzzles.puzzlesource')),
            ],
            options={
                'db_table': 'puzzles',
                'ordering': ['-created_at'],
            },
        ),
    ]
