# Generated by Django 6.0.5 on 2026-05-10 21:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('basic', 'Basic'), ('scientific', 'Scientific'), ('trigonometric', 'Trigonometric'), ('algebra', 'Algebra'), ('calculus', 'Calculus'), ('graph', 'Graphing')], default='basic', max_length=20)),
                ('expression', models.TextField()),
                ('result', models.TextField()),
                ('inputs', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_history', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Calculation History',
                'verbose_name_plural': 'Calculation Histories',
                'db_table': 'calculation_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomFunction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('definition', models.JSONField()),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_functions', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Custom Function',
                'verbose_name_plural': 'Custom Functions',
                'db_table': 'custom_functions',
                'ordering': ['name'],
                'unique_together': {('creator', 'name')},
            },
        ),
    ]
